### ISSUE TITLE
we have earth_radius.f90 and earth_radius_mod.f90 - do we need both?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#101]
We seem to have two copies of the code in earth_radius.f90, one is a module, one just a plain subroutine.

Do we need both?

@kgerheiser this seems like a byproduct of the ip2 merge. Can we remove the non-module version?

**Comment by edwardhartnett** [comment]
@kgerheiser and @GeorgeGayno-NOAA any comments on this one?

**Comment by edwardhartnett** [comment]
@kgerheiser and @GeorgeGayno-NOAA any comments on this one?

**Comment by GeorgeGayno-NOAA** [comment]
> @kgerheiser and @GeorgeGayno-NOAA any comments on this one?

I would guess we don't need two versions. When the unit tests are run, don't we profile which routines are accessed?

**Comment by kgerheiser** [comment]
The code is identical. It should be safe to remove the non-module version.

**Comment by edwardhartnett** [comment]
And yet when I try it:

```
[ 91%] Linking Fortran executable test_vector_grib1
/usr/bin/ld: ../src/libip_d.a(spectral_interp_mod.F90.o): in function `__spectral_interp_mod_MOD_polatev4_grib2':
/home/ed/NCEPLIBS-ip/src/spectral_interp_mod.F90:1046: undefined reference to `earth_radius_'
/usr/bin/ld: /home/ed/NCEPLIBS-ip/src/spectral_interp_mod.F90:1081: undefined reference to `earth_radius_'
/usr/bin/ld: ../src/libip_d.a(spectral_interp_mod.F90.o): in function `__spectral_interp_mod_MOD_polates4_grib2':
/home/ed/NCEPLIBS-ip/src/spectral_interp_mod.F90:411: undefined reference to `earth_radius_'
/usr/bin/ld: /home/ed/NCEPLIBS-ip/src/spectral_interp_mod.F90:442: undefined reference to `earth_radius_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_vector_grib1.dir/build.make:87: tests/test_vector_grib1] Error 1
make[1]: *** [CMakeFiles/Makefile2:1074: tests/CMakeFiles/test_vector_grib1.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

Could it be that we need a USE statement? I put one in spectral_interp_mod.F90 and that seemed to fix it. PR up shortly.
