### ISSUE TITLE
what is the difference between IPXWAFS3 and IPXWAFS2?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#102]
They both have identical documentation.

There is a lot of cut and paste coding going on here! This yields many more lines of code than are needed. More lines of code = greater maintenance and testing expense.

@GeorgeGayno-NOAA can you shed any light on this?

**Comment by GeorgeGayno-NOAA** [comment]
These routines are very similar and could likely be combined. `ipxwafs` uses linear interpolation; `ipxwafs2` uses linear interpolation and accounts for bitmapped data; `ipxwafs3` uses neighbor interpolation and bitmapped data.

**Comment by edwardhartnett** [comment]
OK, I have added this info to the documentation.
