### ISSUE TITLE
change C function name

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#109]
We have C APIs for some functions in ip2lib.h:

```
void gdswzd(long igdtnum, long *igdtmpl, long igdtlen, long iopt,
            long npts, double fill, double *xpts, double *ypts, 
            double *rlon, double *rlat, long *nret,
            double *crot, double *srot, double *xlon, double *xlat,
            double *ylon, double *ylat, double *area);

void gdswzd_grib1(long kgds, long iopt, long npts, double *fill, double *xpts,
		  double *ypts, double *rlon, double *rlat, long nret, double *crot,
		  double *srot, double *xlon, double *xlat, double *ylon,
		  double *ylat, double *area);

```

But then we have a different prototype of the gdswzd() function in iplib.h:

```
void gdswzd(long *kgds, long iopt, long npts, double fill,
            double *xpts, double *ypts, double *rlon, double *rlat,
            long *nret,
            double *crot, double *srot, double *xlon, double *xlat,
            double *ylon, double *ylat, double *area);

```

What is going on with this?

Who uses this C API? @GeorgeGayno-NOAA and @kgerheiser do you know?

**Comment by GeorgeGayno-NOAA** [comment]
wgrib2 uses iplib, and that is written in 'C'.

**Comment by edwardhartnett** [comment]
Is iplib a separate library? I thought that was just a casual version of NCEPLIBS-ip.

It would be good if we could combine the two header files into one. But in C we cannot have two functions with the same name. That's not possible. So clearly one of these function names has to change. That will be a problem for any users, but one they can easily solve by just changing the function name.

I suggest we change the ip2lib.h version to void gdswxd_ip2().

@kgerheiser this seems related to the merger of the ip2 library.

**Comment by AlexanderRichert-NOAA** [comment]
I'm just looking at this in depth-- It doesn't appear to me that the definition in iplib_{4,d,8}.h refers to anything. The arguments don't match at all with what's in gdswzd_c.F90, so I don't know when or how they would ever get used (and it's not used in the unit tests. @GeorgeGayno-NOAA do you happen to know of any codes that use gdswzd specifically? I looked in wgrib2 and didn't see anything. Unless I'm missing something, I think it would make sense to remove the iplib_?.h files altogether, rename the ip2lib_?.h files to iplib_?.h, and leave the C function names as they are.

**Comment by edwardhartnett** [comment]
Yes, agree. Let's do that and if there is a problem from any user, they can let us know.

I also looked at those headers and was confused as to their purpose.
