### ISSUE TITLE
Implement v3.0.2

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/NCEPLIBS-ip#11]
GFS v16 requires v3.0.2.  The v3.0.2 tag has old release notes.  Update the notes and make any other required changes.

Following the Gitflow method, a support branch will be created from the v3.0.2 tag.  Once the branch is working, I can recreate the v3.0.2 tag.

**Comment by GeorgeGayno-NOAA** [comment]
NCO requested a Cray/haswell version for Cray.  Dexin's build system does not support that compiler.  Also, I noticed the openmp flag is not being used.  Make these updates.

**Comment by Hang-Lei-NOAA** [comment]
Thanks George for the updates.

**Comment by kgerheiser** [comment]
Is this necessary for all libraries?

**Comment by Hang-Lei-NOAA** [comment]
I would think that may not be, since we will push cmake after this code
delivery to NCO.

**Comment by GeorgeGayno-NOAA** [comment]
The include files for calling the library from 'c' code were removed for some reason.  Add those back.  These missing files would have been caught if the unit and regression tests were run before merging.  However, these tests were never updated for the new build system and are not able to be compiled.  I will use the tests from v3.0.1 to verify everything is working.

**Comment by kgerheiser** [comment]
I'll work on adding the regression tests to CMake

**Comment by GeorgeGayno-NOAA** [comment]
> I'll work on adding the regression tests to CMake

Thanks.  I thought you already added the tests for some libraries.

**Comment by GeorgeGayno-NOAA** [comment]
I ran the two unit tests on Dell (tests at c2db5e0) using the library/include files from the support branch at 74d5e84.  Both passed.  Will recreate the tag for NCO.  

Also ran the unit test on Cray using the Cray build of the library.  It passed.

**Comment by kgerheiser** [comment]
~~I have a question. Why are all of your commits the same, like `"support/ip_v3.0.2 This commit references #11`? Do you use some tool for git that does this?~~


I see now, there's a little box that expands with the commit

**Comment by GeorgeGayno-NOAA** [comment]
> ~I have a question. Why are all of your commits the same, like `"support/ip_v3.0.2 This commit references #11`? Do you use some tool for git that does this?~
> 
> I see now, there's a little box that expands with the commit

It is just how I like to start the commit message.  It helps me remember what branch I am working from.  And the commit gets tagged to the issue.  Maybe there is a better or official github way to write the commit messages.

**Comment by edwardhartnett** [comment]
This is complete, correct?

**Comment by GeorgeGayno-NOAA** [comment]
> This is complete, correct?

Yes, you can close it.
