### ISSUE TITLE
Some mystery functions mentioned in user_guide.md

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#111]
Here's a screenshot from the built documentation. Note the last function is not hyper-linked:

![image](https://user-images.githubusercontent.com/38856240/175343872-88bddd25-5a4e-4fa6-a2e4-7a64b3d2b77c.png)

So what is ijkgds0/1?

I cannot find any functions of this name...

**Comment by kgerheiser** [comment]
I thought `ijkgds` was not a very descriptive name and it's `field_pos`

https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/ad3255193e53f241852bfded263b229aeb35f5b7/src/ip_grid_mod.F90#L184-L244

**Comment by edwardhartnett** [comment]
I have made this change in the docs.
