### ISSUE TITLE
where are the ploate() functions?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#112]
In the docs we have:

![image](https://user-images.githubusercontent.com/38856240/175569735-5c4363a4-343e-4ed0-94dc-265837192867.png)

Yet I cannot find any functions named polates0(), polates1(), etc.

**Comment by GeorgeGayno-NOAA** [comment]
Those names are from the old GRIB1 IP library. They have been renamed in the current library -

- `polates0` was replaced by `bilinear_interp_mod.F90`
- `polates1` was replaced by `bicubic_interp_mod.F90`
- `polates2` was replaced by `neighbor_interp_mod.F90`
- `polates3` was replaced by `budget_interp_mod.F90`
- `polates4` was replaced by `spectral_interp_mod.F90`
- `polates6` was replaced by `neighbor_budget_interp_mod.F90`

As an FYI, in polates, the 's' refers to scalars. The old library had separate routines for vectors, named polatev. Both functions were combined in the current library.

**Comment by GeorgeGayno-NOAA** [comment]
Oops. Looks like we retained separate routines for vectors and scalars. For example, see `interpolate_bilinear_scalar` and `interpolate_bilinear_vector`.

**Comment by edwardhartnett** [comment]
I have added all this info to the documentation.
