### ISSUE TITLE
what should be the documentation for the ip_station_points_grid_mod?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#115]
What should be the documentation for the ip_station_points_grid_mod?

It currently says:

```
!> @file
!> @brief ???
!>
!> @author Iredell @date 96-04-10

!> @brief ???
!>
!> @author Iredell @date 96-04-10
module ip_station_points_grid_mod
```
@GeorgeGayno-NOAA do you know?

**Comment by GeorgeGayno-NOAA** [comment]
That is a new routine written by @kgerheiser? I suspect it is used for interpolating gridded data to a series of random station points (instead of another grid).  So you can say something like - "Interpolate gridded data to a series of station points."

**Comment by kgerheiser** [comment]
My terminology may be off, but there was a special case in the doc blocks that used `station points` as a possible "grid" and I just took that.

**Comment by edwardhartnett** [comment]
@kgerheiser can you elaborate on your answer? I don't understand what you mean.

What should be the documentation for this module?

Is this module used by any operational code anywhere? Are you saying it can be removed?

**Comment by edwardhartnett** [comment]
@kgerheiser can I get more info on this module please? I need to complete the documentation, which is currently empty:

```
!> @file
!> @brief ???
!>
!> @author Kyle Gerheiser @date ???

!> @brief ???
!>
!> @author Kyle Gerheiser @date ???

```

What should it say?
