### ISSUE TITLE
recover test for ipxwafs.F90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#121]
We have ipxwafs.F90, which has zero testing.

Is anyone using this subroutine? @GeorgeGayno-NOAA or @kgerheiser do you know?

Here's what the documentation says:

```
!> @brief Expand or contract wafs grids.
!>
!> This subprogram transforms between the thinned wafs grids used for
!> transmitting to the aviation community and their full expansion as
!> used for general interpolation and graphics.

```

**Comment by GeorgeGayno-NOAA** [comment]
We still produce GRIB1 and GRIB2 WAFS data from GFS. On Dell, these files are here - `/gpfs/dell1/nco/ops/com/gfs/prod/gfs.20220627/00/atmos/wmo`

So, I don't think we can get rid of it.

**Comment by edwardhartnett** [comment]
The next question (inevitably) is: how do we test it?

Do we need a data file to start with? If so, is there a particularly small one we can use?

**Comment by GeorgeGayno-NOAA** [comment]
I wrote a test for this. See the ip2 repo - https://github.com/NOAA-EMC/NCEPLIBS-ip2/tree/develop/tests/reg_tests/ipxwafs

**Comment by AlexanderRichert-NOAA** [comment]
Fixed by https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/121
