### ISSUE TITLE
questions about spectral_interp_mod

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#123]
@GeorgeGayno-NOAA can I have some help with spectral_interp_mod?

My first question is: which of the grids listed here does this code relate to:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-1.shtml

There are three spectral grids listed here, Mercator, Polar Stereographic, and Lambert conformal...

Some of the documentation:

 ```
 !> Interpolate scalar fields (spectral).
  !>
  !> This subprogram performs spectral interpolation from any grid to
  !> any grid for scalar fields. It requires that the input fields be
  !> uniformly global. Options allow choices between triangular shape
  !> (ipopt(1)=0) and rhomboidal shape (ipopt(1)=1) which has no
  !> default; a second option is the truncation (ipopt(2)) which
  !> defaults to a sensible truncation for the input grid (if
  !> opt(2)=-1).
  !>
  !> @note If the output grid is not found in a special list, then the
  !> transform back to grid is not very fast. This special list
  !> contains global cylindrical grids, polar stereographic grids
  !> centered at the pole and mercator grids.
  !>
  !> Only horizontal interpolation is performed.
  !>
  !> The code recognizes the following projections, where "igdtnumi/o"
  !> is the GRIB2 grid defintion template number for the input and
  !> onutput grids, respectively:
  !> - igdtnumi/o = 00 equidistant cylindrical
  !> - igdtnumo = 01 rotated equidistant cylindrical. "e" and non-"e" staggered
  !> - igdtnumo = 10 mercator cylindrical
  !> - igdtnumo = 20 polar stereographic azimuthal
  !> - igdtnumo = 30 lambert conformal conical
  !> - igdtnumi/o = 40 gaussian cylindrical
  !>
  !> As an added bonus the number of output grid points and their
  !> latitudes and longitudes are also returned. On the other hand,
  !> the output can be a set of station points if igdtnumo < 0, in which
  !> case the number of points and their latitudes and longitudes must
  !> be input. Output bitmaps will not be created.


```

**Comment by GeorgeGayno-NOAA** [comment]
Are you talking about the special grids? According to the logic, the 'special cases' include: 
- Equidistant cylindrical ('0') and gaussian cylindrical grids ('40') that have an even number of points in the 'i' direction, with a western boundary at Greenwich, and have a scan mode of '0'. 
- Any mercator grid ('10'). 
- And a polar stereographic grid ('20') with an odd number of points that are the same in the 'i' and 'j' direction, the 'i' and 'j' resolution is the same, and the scan mode is '64'.

**Comment by edwardhartnett** [comment]
I am first trying to identify which  of the grids listed here does this code relate to:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-1.shtml

There are three spectral grids listed:

```
61 | Spectral Mercator with modelling subdomains definition (See Template 3.61)
62 | Spectral Polar Stereographic with modelling subdomains definition (See Template 3.62)
63 | Spectral Lambert conformal with modelling subdomains definition (See Template 3.63)


```

Does the spectral_interp_mod handle all three of these?

**Comment by GeorgeGayno-NOAA** [comment]
> I am first trying to identify which of the grids listed here does this code relate to: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-1.shtml
> 
> There are three spectral grids listed:
> 
> ```
> 61 | Spectral Mercator with modelling subdomains definition (See Template 3.61)
> 62 | Spectral Polar Stereographic with modelling subdomains definition (See Template 3.62)
> 63 | Spectral Lambert conformal with modelling subdomains definition (See Template 3.63)
> ```
> 
> Does the spectral_interp_mod handle all three of these?

No, it does not. IP does not recognize any of those grids. 'Spectral' refers to the interpolation method, not the grid.
