### ISSUE TITLE
how to buid NCEPLIBS-ip with " use ip_mod ".

### ISSUE THREAD

**Issue by xiaxiaoxue** [NOAA-EMC/NCEPLIBS-ip#126]
![image](https://user-images.githubusercontent.com/105027799/198501875-add2d073-03c1-4532-8c9f-1fdfbfa57908.png) 
I want to build NCEPLIBS-grib_until with NCEPLIBS-ip，But I encountered an error：
CMakeFiles/copygb.dir/copygb.F.o: In function 'MAIN__' Medium:

**/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 269: for 'makgds_' Undefined reference

CMakeFiles/copygb.dir/copygb.F.o: In the function 'intgrib1':

/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 1363: for 'ipolates_' Undefined reference

/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 1440: for 'ipolatev_' Undefined reference

/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 1410: for 'ipolatev_' Undefined reference

/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 1399: for 'ipolatev_' Undefined reference

/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 1378: for 'ipolatev_' Undefined reference

/public/home/ahsqxt_ 002/software/NCEPLIBS-grib_ Util-1.2.2/sorc/copygb.fd/copygb.F: 1341: for 'ipolates_' Undefined reference**

I think it is caused by compiling NCEPLIBS ip without "use ip_mod".
But I can't understand how to " use the ip library add use ip_mod to your Fortran code"

**Comment by edwardhartnett** [comment]
grib_util does not work yet with ip-4.0.0. Instead, use ip-3.3.3.

**Comment by xiaxiaoxue** [comment]
> 
Yes yes , Thank you so much.
