### ISSUE TITLE
NCO having a problem installing?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#127]
> For the IP library installation, I tested out with partial option 1 (run buildhpcstack.sh only) , but it could not find the yaml file, as the stack file name does not match the name it mentioned in the release note. In release note, it says: "./buildhpcstack.sh prod intel ip_4_0_0"
> 
> 
> 
> [IP_4.0.0 Deliver Notes - Google Docs](https://docs.google.com/document/d/1TXmSnd0mJeg-hO4cZLhDFrbZY-CYvNtebn7V3roxQxA/edit)
> 
>  
> 
> Either with or without the "-y ..." flag and failed:
> 
> 
> 
> "./buildhpcstack.sh para intel ip_4_0_0
> 
> yaml config file 'stack/stack_ip_4_0_0.yaml' does not exist! Exitting..."
> 
>  
> 
> "./buildhpcstack.sh para intel ip_4_0_0 -y ../stack/stack_ip_v4_0_0.yaml
> 
> yaml config file 'stack/stack_ip_4_0_0.yaml' does not exist! Exitting...
> 
> "
> 
>  
> 
> I had to change the ip_4_0_0 to ip_v4_0_0 to match the stack name for it to work
> 
> " ./buildhpcstack.sh para intel ip_v4_0_0 -y ../stack/stack_ip_v4_0_0.yaml"
> 
>  
> 
> So please update the release note to match them, also I found the library names are not consistent, some are with v, and some are not. Please consider keeping the same naming convention so that we don't get into more trouble and confusion. 
> 
>  
> 
> Again, would you please go through the release notes to make sure they are accurate each time when there is delivery?  I heard that the release notes were incorrect before but the similar one is still now just replaced with a different library name. We don't want each time whoever in SPA team is new to the hpc stack library installation on WCOSS2 follow an incorrect or inaccurate procedure and spend too much time figuring out the right way to do it.
> 
>  
> 
> Would you please check the scripts/files in the delivery as well to make sure they are correct as well?
> 
> 
> 
> Sorry for the long email. This is what  I have  so far. Please let me know if you have any questions or suggestions.  
> 
>  
> 
> Thanks!
> 
>  
> 
> Jen

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA has this been resolved?

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA has this been resolved?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it is solved
