### ISSUE TITLE
Create single field versions of ipolate[s,v] for GRIB2

### ISSUE THREAD

**Issue by EricEngle-NOAA** [NOAA-EMC/NCEPLIBS-ip#130]
In ipolates.F90 and ipoloatev.F90, generic interfaces exist for top-level interpolation subroutines for GRIB1 and GRIB2 objects.  A single-field version of ipolate[s,v] exists for GRIB1, but not for GRIB2.

**Comment by edwardhartnett** [comment]
@EricEngle-NOAA are you going to add this functionality?

I don't have any programmer available to work on this...

**Comment by EricEngle-NOAA** [comment]
@edwardhartnett Yes, I can work on this.  I think it would be a good idea to merge PR #128 so I could start with a clean fork.

**Comment by EricEngle-NOAA** [comment]
@edwardhartnett It seems I already did this work back in Nov/Dec 2022.  ipolate[s,v].F90 sources do contain single field versions for GRIB2.
