### ISSUE TITLE
are we handling static/shared libraries in the best way possible?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#140]
@aerorahul recently we have updated the way NCEPLIBS-sp and NCEPLIBS-sp handle shared and static libraries. We now:
* Provide options to build or not build shared/static.
* Set the SOVERSION.

You can see what we are doing in the CMakeLists.txt file and the src/CMakeLists.txt file of the develop branch of this repo.

I am about to apply these changes to all the NCEPLIBS libraries. But are they correct and the most compact way to express this? I would very much value your opinion...

Although I am learning CMake and continue to do so I'm still no expert.

**Comment by aerorahul** [comment]
@edwardhartnett 
Thank you for sharing the solution for building shared and static libraries.
I took a look and I think there is a better way to build both (or either) libraries without doubling the compile time.
In the current approach, one is building two sets of libraries lib_shared and lib_static.  That in itself doubles the compile time.
Then, to link with static or shared, one has to explicitly specify which type to use at linking time.

I believe there is a better solution which will:
1. eliminate the double compilation
2. allow seamless use in the calling package.  HDF5 does this by setting a higher level flag such as `set(HDF5_SHARED_LIBS YES)` followed by `find_package(HDF5)`.  This will only find the shared library and will use it at link time.

I can try and open a PR with an example in `sp` or `ip` if that would help explaining this better.

**Comment by edwardhartnett** [comment]
Yes an example would help very much!

This is actually the work of @EricEngle-NOAA and he would like a release of sp/ip with these supported in support of the GRIB2 python library.

Whatever we figure out here will be used for all the NCEPLIBS...

**Comment by aerorahul** [comment]
I will take this on.  Should have something working by end of next week.  Please ping me if that timeline slips.
I don't think it is a lot of work.

**Comment by edwardhartnett** [comment]
@aerorahul any progress? We would like to do an sp release. It's not super-urgent but is the first in a long series of new NCEPLIBS releases. So we would like to get going... ;-)

But we want shared/static working well in all these new releases.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA not sure how much of a CMake expert you have become, but your input is welcome. We are adding shared/static build support to the NCEPLIBS. Are we doing it right?

Take a look in NCEPLIBS-ip or NCEPLIBS-sp for an example of what we are doing to add support the two CMake options BUILD_SHARED_LIBS and BUILD_STATIC_LIBS.

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett I'll take a look. Of what I see in NCEPLIBS-ip, it seems reasonable. I think theoretically the option for shared can be added without an explicit "add_library" call, but I'll have to see...

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett I think src/CMakeLists.txt for ip and sp look reasonable. The only potential concern I can think of is that the automatically generated {sp,ip}-config.cmake does not allow users to decide whether to use the static or the shared library. But I would imagine on most systems it'll be one or the other anyway.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA can you elaborate on the config.cmake issue? I don't know much about that...

**Comment by AlexanderRichert-NOAA** [comment]
Sure-- From what I can tell, cmake doesn't "like" to support having static and shared builds at the same time. It is possible to both build both (obviously, since that's we're doing here) and it's possible to make cmake configs that can allow the user to choose one or the other, but I don't think that's a functionality that cmake automatically provides. I'm actually not sure how cmake will behave when another package calls "find_library" on, say, ip, and static and shared are both present.

**Comment by aerorahul** [comment]
@AlexanderRichert-NOAA 
CMake actually does provide the ability to create both static and shared (but by only building the shared), but that is currently only supported for C, C++ projects.
The support is explained in `generate_export_header`.
There is no such support for Fortran projects, so we have to explicitly build both libraries (as is done in sp).

The configs can (and should) be able to handle either of those with the `default` to whatever the developer wants to be used.
This can be done with options such as: `IP_USE_STATIC_LIBRARIES` or `IP_USE_SHARED_LIBRARIES`.
Obviously, both cannot be `True` at the same time.
Once one of them is set, `find_package(ip)` will return the library `ip::ip_${kind}`, that is agnostic of whether the target is `shared` or `static`.
The `ip-config.cmake` will create this alias based on the user request.

**Comment by edwardhartnett** [comment]
@aerorahul do you think we have a good solution in our ip and sp CMake files for shared/static?

We are about to do releases, so this is the time to bring up problems...

**Comment by aerorahul** [comment]
I don't think it is appropriate for the user to have to hard-wire `_static` or `_shared` in their project.
Unfortunately, I have too many things on my plate right now, for me to do this work before next week.

**Comment by edwardhartnett** [comment]
OK, I spent some time reading about this topic. This was particularly helpful: https://cgold.readthedocs.io/en/latest/tutorials/libraries/static-shared.html#right-way

A key insight is that, unlike autotools, cmake wants us to build either a shared or a static, but not both. And, though it does not try and enforce this, cmake thinks you should install static and shared in different directories.

Once we adopt this approach, everything becomes simpler. The default is static, the BUILD_SHARED_LIBS option builds shared instead.

@aerorahul @EricEngle-NOAA @AlexanderRichert-NOAA please take a look and tell me what you think.

**Comment by aerorahul** [comment]
@edwardhartnett @EricEngle-NOAA @AlexanderRichert-NOAA 
2 PRs for your reviews; one each in SP and IP.
https://github.com/NOAA-EMC/NCEPLIBS-sp/pull/102
https://github.com/NOAA-EMC/NCEPLIBS-ip/pull/145

The CI in the `NCEPLibs-ip` PR https://github.com/NOAA-EMC/NCEPLIBS-ip/pull/145 might fail as it depends on `NCEPLibs-sp` to be built and installed as mentioned in https://github.com/NOAA-EMC/NCEPLIBS-sp/pull/102

**Comment by aerorahul** [comment]
> OK, I spent some time reading about this topic. This was particularly helpful: https://cgold.readthedocs.io/en/latest/tutorials/libraries/static-shared.html#right-way
> 
> 
> 
> A key insight is that, unlike autotools, cmake wants us to build either a shared or a static, but not both. And, though it does not try and enforce this, cmake thinks you should install static and shared in different directories.
> 
> 
> 
> Once we adopt this approach, everything becomes simpler. The default is static, the BUILD_SHARED_LIBS option builds shared instead.
> 
> 
> 
> @aerorahul @EricEngle-NOAA @AlexanderRichert-NOAA please take a look and tell me what you think.

I don't know why this person thinks we need to have separate installation directories for shared and static libraries. CMake does not enforce it because I don't believe it is necessary.  The objects (.o) and modules (.mod) have no bearing on static or shared. A library is an archive (static), compiled object (shared), but both are unique. So them being in the same directory does not (to my knowledge) have any impacts on each other. 
Do others see things differently?

**Comment by edwardhartnett** [comment]
The reason that CMake doesn't like to put shared and static in the same place is that it does not work on Windows, where there is some name conflict. See the article for more details.

But that does not really matter to us, right? If you are on a Linux system and want to install both static and shared to the same directory, then you can do so.

But the question is, do we think this PR represents a good way to do shared libraries with CMake.

**Comment by edwardhartnett** [comment]
OK, I spent a bunch of time reading CMake docs, and I think the solution I present in #144 is correct.

The CMake way is different from the autotools way. I have been an autotools fan for years, but when using CMake, I think following CMake conventions would be best. It's clear from the CMake documentation here, that we are expected to build either shared or static, but not both at the same time: https://cmake.org/cmake/help/v3.0/command/add_library.html. It says:

`If no type is given explicitly the type is STATIC or SHARED based on whether the current value of the variable BUILD_SHARED_LIBS is ON. For SHARED and MODULE libraries the POSITION_INDEPENDENT_CODE target property is set to ON automatically.
`

Reading further on stackoverflow and other sites, it's clear that, though there are many proposed hacks to emulate the autotools behavior, the default cmake behavior is that for each invocation of cmake, you build either shared or static. If you want both, run CMake twice and build twice. That's the CMake way of doing libraries.

When we follow the CMake way, we have much less code to maintain. We get static libraries by default, which matches our current behavior, and we don't have to do anything to tell packages like ip to build with static or shared sp. ip will build with whatever sp you point it at, static or shared. (If both exist, static will be selected.)

This all seems like perfectly acceptable behavior to me. When I test it on my machine, with both shared and with static, everything works.

So why complicate things? Do we have some reason to prefer building libraries the autotools way? Let's just do things as CMake expects them to be done, and take the easy way out.

**Comment by aerorahul** [comment]
@edwardhartnett #144 is basically duplicating #145

**Comment by edwardhartnett** [comment]
@aerorahul please check again. #144 is different in a number of ways:
* Far fewer lines of cmake code.
* Does not build static and/or shared, instead builds static or shared.
* Does not require changes in other projects to use static vs. shared.
* Does not build static if only shared is required.
* Does not require that tests only work against static.

I believe that #144 is a superior solution that works in accordance with cmake's ways of building static/shared.

Since this solution is going to be applied to the other NCEPLIBS libraries, a compact and easy to maintain solution is to be preferred.

**Comment by aerorahul** [comment]
Yes, you removed the excess cmake lines that I removed in #145 
Does your PR create both static and shared at the same time? I don't think it does.  You have to choose before hand.
This also means that any dependent library needs to know before hand how this library was built.  So if this library was built in shared, then it has to use the shared (static is not present)
The PR #145 was inspired by the discussion on this thread on how to handle static/shared the best way.
Your proposal is to not handle both, but rather just handle one.  Is that the best way?  I don't know.

Either way, I am happy to close the PRs.

**Comment by edwardhartnett** [comment]
A key question is whether static and shared will be created at the same time or in separate cmake runs.

Autotools wants to build both at once.

CMake wants to build one or the other.

Let's try the CMake way. I think it will work fine for us.

**Comment by aerorahul** [comment]
Here is an example from an "Industry-wide" used software.
https://github.com/HDFGroup/hdf5/blob/develop/src/CMakeLists.txt
