### ISSUE TITLE
Interpolate to station points is not working

### ISSUE THREAD

**Issue by EricEngle-NOAA** [NOAA-EMC/NCEPLIBS-ip#167]
The online and internal code documentation states the ability to interpolate from a source grid to stations, however this feature is not working at this time.

**IMPORTANT** I have identified the issues and have it working and will submit a PR soon

**Comment by EricEngle-NOAA** [comment]
PR #168 provides fully working interpolation to station points.

**Comment by AlexanderRichert-NOAA** [comment]
Fixed by #168
