### ISSUE TITLE
Do 4.1.0 release

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-ip#178]
- [x] Update issues/projects.
- [x] Update VERSION file.
- [x] Build docs and put them on gh-pages branch (incl. #75).
- [x] Edit release notes.
- [x] Do release on GitHub.
- [x] Draft next version release notes and start next version project.
- [x] Add new version to Spack recipe.

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett do you mind giving the [release notes](https://github.com/NOAA-EMC/NCEPLIBS-ip/releases/tag/untagged-e87c40d70e4e92958b0d) a quick look and if all looks good I'll do the release?

**Comment by edwardhartnett** [comment]
Looks great!

**Comment by AlexanderRichert-NOAA** [comment]
Spack PR went through; new project & release draft created.
