### ISSUE TITLE
do we really need pfUnit? 

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#18]
It seems that there is some testing framework needed by the build: pfUnit.

Testing frameworks are considered harmful! Note that other science software packages in our stack don't use them.

We are asking users to run tests on the software, but to do that, they must first install this test framework? Well, no one will do that - they will just skip running our tests. So we are shooting ourselves in the foot, because having users run tests is the most cost-effective way to handle problems. If the tests fail, that saves everyone the time and trouble of investigating whatever user code is going to use the library, and then fail.

Both CMake and autotools provide full and complete support for unit testing, including in Fortran, including with MPI and multi-processor testing. The NetCDF, HDF5, and pnetcdf packages all face these same issues, and do not use any kind of testing framework, other than those provided by the build systems. All of these packages have significant fortran tests, and significant parallel I/O testing.

The GFDL people on the FMS project (and others) also were using a test framework (a different one, called "bats"). For the same reasons I outlined above, they recently removed it and have followed the example of other packages by using the built-in testing frameworks of autotools/CMake. (Which are very full-featured and have many interesting bells and whistles if you are interested in improving test output or experience.)

Part of the appeal of this framework may be the transition to fully automated testing. For those used to manual testing, a testing framework may seem to provide value. But with automated testing, test output is rarely examined. It either succeeds completely, or fails. So there is little need for any framework to help with manual test running. All that is done by the CI systems anyway.

**Comment by edwardhartnett** [comment]
@kgerheiser we discussed this today. I know it's hard to let go, but I don't think we can require this testing framework to run tests.

The reason is that we are putting a barrier between users and testing. We want users to test - that's much better. So we must make it easy for them.

**Comment by kgerheiser** [comment]
Yeah, that's fine. How do you write unit-tests? Each one is a single `program`?

**Comment by edwardhartnett** [comment]
You write a program in Fortran or C, and it does stuff and checks results. If everything works, it exists with 0, otherwise with non-zero. 

Here's an example:
https://github.com/Unidata/netcdf-fortran/blob/master/nf_test4/ftst_vars2.F

So the program can do as many things as you want, and netcdf-c has one very, very long program with multiple code files called nc_test, which tests EVERYTHING, all in one giant program. However, such programs become hard to debug when there is a problem.

Better to accept that there will be some test code duplication, and have a bunch of programs, each of which tests some subset of functionality. Then, when something breaks, you are only dealing with a small self-contained program instead of a giant monster.
