### ISSUE TITLE
Build warning with gfortran-11

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#183]
cd /home/ed/NCEPLIBS-ip/b/src && /usr/bin/gfortran -DLSIZE=4 -I/home/ed/NCEPLIBS-ip/b/src/include_4 -g  -fbacktrace -fconvert=big-endian -cpp  -O0 -ggdb -Wall -fcheck=all -Jinclude_4 -c /home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90 -o CMakeFiles/ip_4.dir/ip_station_points_grid_mod.F90.o
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:41:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |                                         1
Warning: Dummy argument ‘area’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:11:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |           1
Warning: Dummy argument ‘crot’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:76:11:

   76 |        FILL,XPTS,YPTS,RLON,RLAT,NRET, &
      |           1
Warning: Unused dummy argument ‘fill’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:75:44:

   75 |   SUBROUTINE GDSWZD_station_points(self,IOPT,NPTS, &
      |                                            1
Warning: Unused dummy argument ‘iopt’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:76:31:

   76 |        FILL,XPTS,YPTS,RLON,RLAT,NRET, &
      |                               1
Warning: Unused dummy argument ‘rlat’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:76:26:

   76 |        FILL,XPTS,YPTS,RLON,RLAT,NRET, &
      |                          1
Warning: Unused dummy argument ‘rlon’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:75:39:

   75 |   SUBROUTINE GDSWZD_station_points(self,IOPT,NPTS, &
      |                                       1
Warning: Unused dummy argument ‘self’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:16:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |                1
Warning: Dummy argument ‘srot’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:26:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |                          1
Warning: Dummy argument ‘xlat’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:21:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |                     1
Warning: Dummy argument ‘xlon’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:76:16:

   76 |        FILL,XPTS,YPTS,RLON,RLAT,NRET, &
      |                1
Warning: Unused dummy argument ‘xpts’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:36:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |                                    1
Warning: Dummy argument ‘ylat’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:77:31:

   77 |        CROT,SROT,XLON,XLAT,YLON,YLAT,AREA)
      |                               1
Warning: Dummy argument ‘ylon’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:76:21:

   76 |        FILL,XPTS,YPTS,RLON,RLAT,NRET, &
      |                     1
Warning: Unused dummy argument ‘ypts’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:48:37:

   48 |   subroutine init_grib2(self, g2_desc)
      |                                     1
Warning: Unused dummy argument ‘g2_desc’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:48:28:

   48 |   subroutine init_grib2(self, g2_desc)
      |                            1
Warning: Unused dummy argument ‘self’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:37:37:

   37 |   subroutine init_grib1(self, g1_desc)
      |                                     1
Warning: Unused dummy argument ‘g1_desc’ at (1) [-Wunused-dummy-argument]
/home/ed/NCEPLIBS-ip/src/ip_station_points_grid_mod.F90:37:28:

   37 |   subroutine init_grib1(self, g1_desc)
      |                            1
Warning: Unused dummy argument ‘self’ at (1) [-Wunused-dummy-argument]

**Comment by AlexanderRichert-NOAA** [comment]
Fixed by #188
