### ISSUE TITLE
Reorganize flags for real/int defaults in testing

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-ip#189]
Instead of always building the test executables with default real size 8 and setting different sizes for specific variables, let's use the same flags as for building the library to reduce clutter in the test code. Arguably this is also more realistic since developers will typically use the ip _4/_8/_d version that corresponds with the default settings for their code.

**Comment by edwardhartnett** [comment]
I'm not sure this is a good idea.

Instead I have been trying to eliminate the need for 4/8/d builds. I think we should only do the 4 build, and it should handle all types.
