### ISSUE TITLE
New Fortran module `constants_mod` is creating problems

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS-ip#197]
## Description

copy and paste from slack ...

The new `ip@4.1.0` is going to create a real problem. I look at the changes between the current and new tag https://github.com/NOAA-EMC/NCEPLIBS-ip/compare/v3.3.3...v4.1.0 and I see that a Fortran module is created that is called `constants_mod` that gets installed in the typical include directories.

FMS also has a `constants_mod`, and probably a lot of other legacy packages as well. That means depending on which `-I` comes first in a compile command that requires `ip` , `fms`, etc. the outcome is different. It’s already causing problems for JEDI, because the CI containers can no longer find the `fms` constants module and compilation fails with (cont’d below):
```
[ 93%] Building Fortran object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/VariableChange/VertRemap/fv3jedi_vc_vertremap_mod.f90.o
cd /root/test/build-release/fv3-jedi/src/fv3jedi && /usr/bin/gfortran -DENABLE_GSIBEC=1 -DGSW_FOUND -DH5_BUILT_AS_DYNAMIC_LIB -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200809L -Dfv3jedi_EXPORTS -Dioda_SHARED=1 -Dioda_fortran_SHARED=1 -I/root/test/jedi-bundle/fv3-jedi/src/fv3jedi -I/root/test/jedi-bundle/fv3-jedi/src -I/root/test/build-release/fv3-jedi/src -I/root/test/build-release/fv3-jedi/module -I/root/test/build-release/oops/include -I/root/test/jedi-bundle/oops/src -I/root/test/build-release/module/oops/GNU/9.4.0 -I/root/test/jedi-bundle/saber/src/saber/.. -I/root/test/build-release/module/saber/GNU/9.4.0 -I/root/test/jedi-bundle/vader/src -I/root/test/build-release/gsw/module -I/root/test/jedi-bundle/ufo/src -I/root/test/build-release/ufo/module -I/root/test/build-release/ioda/include -I/root/test/build-release/module/ioda/GNU/9.4.0 -I/root/test/jedi-bundle/ioda/src/engines/ioda/include -I/root/test/jedi-bundle/ioda/src/engines/ioda/fortran -I/root/test/build-release/ioda/src/engines/ioda/fortran -I/root/test/build-release/ioda/src/engines/ioda/config -I/root/test/build-release/module/crtm/GNU/9.4.0 -I/root/test/build-release/femps/module -I/root/test/build-release/fv3-jedi-lm/module -I/root/test/build-release/fv3/module -I/opt/software/linux-ubuntu20.04-x86_64/gcc-9.4.0/netcdf-fortran-4.6.0-lhpdyyys36kcffvybdbvsbl43pva4k2g/include -I/opt/software/linux-ubuntu20.04-x86_64/gcc-9.4.0/netcdf-c-4.9.2-efnd67ozloy7tmvo5hxnms75etjbx7lx/include -I/opt/software/linux-ubuntu20.04-x86_64/gcc-9.4.0/openmpi-4.1.5-hm3va3m5sqrg4r6ryu7a2awk7bi2serv/include -I/opt/software/linux-ubuntu20.04-x86_64/gcc-9.4.0/openmpi-4.1.5-hm3va3m5sqrg4r6ryu7a2awk7bi2serv/lib -I/opt/view/include/eigen3 -I/opt/view/include/eckit -I/opt/view/module/fckit -I/opt/view/include/fckit -I/opt/view/module/atlas -I/opt/view/module/gsibec/GNU/9.4.0 -I/opt/view/include_d -I/opt/view/include/odc -I/opt/view/include/eckit/sql -I/opt/view/include/atlas -I/opt/view/include/eckit/geometry -I/opt/view/include/eckit/linalg -I/opt/software/linux-ubuntu20.04-x86_64/gcc-9.4.0/eigen-3.4.0-mljottfqworcn4sz3pdg3z3da2o7bcsu/include/eigen3 -I/opt/view/include/eckit/maths -I/opt/view/include/eckit/mpi -I/opt/view/include/eckit/option -I/opt/view/include/atlas_io -I/opt/view/lib/fms/module -I/opt/view/include -O2 -g -DNDEBUG -J../../module -fPIC -fopenmp -pthread -c /root/test/jedi-bundle/fv3-jedi/src/fv3jedi/VariableChange/VertRemap/fv3jedi_vc_vertremap_mod.f90 -o CMakeFiles/fv3jedi.dir/VariableChange/VertRemap/fv3jedi_vc_vertremap_mod.f90.o
/root/test/jedi-bundle/fv3-jedi/src/fv3jedi/VariableChange/VertRemap/fv3jedi_vc_vertremap_mod.f90:12:34:

   12 | use constants_mod,           only: grav
      |                                  1
Error: Symbol 'grav' referenced at (1) not found in module 'constants_mod'
/root/test/jedi-bundle/fv3-jedi/src/fv3jedi/VariableChange/VertRemap/fv3jedi_vc_vertremap_mod.f90:217:78:

  217 |   Atm%phis(isc:iec,jsc:jec) = real(orog_filt(isc:iec,jsc:jec,1),kind_fv3)*grav  ! Convert to phis
      |                                                                              1
Error: Symbol 'grav' at (1) has no IMPLICIT type
```
I will note that new FMS versions, newer than what we use at JCSDA at the moment (hoping to upgrade to 2023.02 in the next couple of months) have solved this by providing direct access to `FMSconstants`, but they still maintain a legacy module (wrapper) `constants_mod`. In JEDI, we avoid this lack of namespace problem in Fortran by adding the project name to the constants module, for example `fv3jedi_constants_mod`.

Nevertheless, I think this needs to be fixed. Maybe rename IP's constants module to `ip_constant_mod`? It hopefully isn't used widely outside the `ip` code itself yet, since it was introduced recently.

**Comment by AlexanderRichert-NOAA** [comment]
fyi @edwardhartnett

**Comment by AlexanderRichert-NOAA** [comment]
I just tested changing constants_mod->ip_constants_mod, and it builds correctly and the unit tests run. I've checked grib_util, UPP, and ufs_utils, and none of them use constants_mod (well, ufs_utils uses the fms one but nevermind that). Once I'm fairly sure I'm not missing any dependencies I'll release ip 4.2.1 with this fix.

**Comment by AlexanderRichert-NOAA** [comment]
I think the main thing for now is to make sure everything within spack-stack will build, then we can deal with other applications later (though I think the big applications that use ip mainly do so through grib_util/upp/ufs_utils).

**Comment by climbfuji** [comment]
Thanks for jumping on this right away

**Comment by edwardhartnett** [comment]
Good solution. Does this require any changes in pacakges using ip? They still will do just "use ip" right?

**Comment by AlexanderRichert-NOAA** [comment]
No change in usage, yes-- thankfully none of the packages using ip are directly accessing the constants.
