### ISSUE TITLE
interesting include directory names

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#24]
Instead of the usual "include" directory, this package creates some interesting include directory names:

 ```
 /home/ed/NCEPLIBS/NCEPLIBS-ip:
  total used in directory 24 available 187782844
  drwxrwxr-x 6 ed ed 4096 Sep 30 06:49 .
  drwxrwxr-x 7 ed ed 4096 Sep 30 06:49 ..
  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 include_4
  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 include_8
  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 include_d
  drwxrwxr-x 3 ed ed 4096 Sep 30 06:49 lib

```

Within the include_4 directory, I find:

```
  /home/ed/NCEPLIBS/NCEPLIBS-ip/include_4:
  total used in directory 40 available 187782720
  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 .
  drwxrwxr-x 6 ed ed 4096 Sep 30 06:49 ..
  -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzd00_mod.mod
  -rw-r--r-- 1 ed ed  516 Sep 30 06:48 gdswzd01_mod.mod
  -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzd03_mod.mod
  -rw-r--r-- 1 ed ed  531 Sep 30 06:48 gdswzd04_mod.mod
  -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzd05_mod.mod
  -rw-r--r-- 1 ed ed  516 Sep 30 06:48 gdswzdcb_mod.mod
  -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzdcd_mod.mod
  -rw-r--r-- 1 ed ed  531 Sep 30 06:48 gdswzd_mod.mod

```

Why all the mod files?

**Comment by GeorgeGayno-NOAA** [comment]
> Instead of the usual "include" directory, this package creates some interesting include directory names:
> 
> ```
> /home/ed/NCEPLIBS/NCEPLIBS-ip:
>  total used in directory 24 available 187782844
>  drwxrwxr-x 6 ed ed 4096 Sep 30 06:49 .
>  drwxrwxr-x 7 ed ed 4096 Sep 30 06:49 ..
>  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 include_4
>  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 include_8
>  drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 include_d
>  drwxrwxr-x 3 ed ed 4096 Sep 30 06:49 lib
> ```
> 
> Within the include_4 directory, I find:
> 
> ```
>   /home/ed/NCEPLIBS/NCEPLIBS-ip/include_4:
>   total used in directory 40 available 187782720
>   drwxr-xr-x 2 ed ed 4096 Sep 30 06:49 .
>   drwxrwxr-x 6 ed ed 4096 Sep 30 06:49 ..
>   -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzd00_mod.mod
>   -rw-r--r-- 1 ed ed  516 Sep 30 06:48 gdswzd01_mod.mod
>   -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzd03_mod.mod
>   -rw-r--r-- 1 ed ed  531 Sep 30 06:48 gdswzd04_mod.mod
>   -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzd05_mod.mod
>   -rw-r--r-- 1 ed ed  516 Sep 30 06:48 gdswzdcb_mod.mod
>   -rw-r--r-- 1 ed ed  515 Sep 30 06:48 gdswzdcd_mod.mod
>   -rw-r--r-- 1 ed ed  531 Sep 30 06:48 gdswzd_mod.mod
> ```
> 
> Why all the mod files?

There is a set for each precision version of the library - single, mixed, double.

**Comment by edwardhartnett** [comment]
OK, so this is similar to what is happening with the sp library? See https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/226

If so, we should use fortran interfaces to solve this problem. @GeorgeGayno-NOAA do you agree?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, so this is similar to what is happening with the sp library? See [NOAA-EMC/NCEPLIBS-ip#226](https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/226)
> 
> If so, we should use fortran interfaces to solve this problem. @GeorgeGayno-NOAA do you agree?

That is one way to do it.  I would use double precision for all computations.

**Comment by edwardhartnett** [comment]
I have raised your point here: https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/226.

**Comment by edwardhartnett** [comment]
OK, this is a hard problem. See discussion in NOAA-EMC/NCEPLIBS-sp#76. I will close this issue.
