### ISSUE TITLE
Combine all library builds so only one libip is needed

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#25]
After building this package, in the lib directory, I see several libraries. What's the difference between them?

```
/home/ed/NCEPLIBS/NCEPLIBS-ip/lib:
  total used in directory 2552 available 187783064
  drwxrwxr-x 3 ed ed   4096 Sep 30 06:49 .
  drwxrwxr-x 6 ed ed   4096 Sep 30 06:49 ..
  drwxrwxr-x 3 ed ed   4096 Sep 30 06:49 cmake
  -rw-r--r-- 1 ed ed 855098 Sep 30 06:48 libip_4.a
  -rw-r--r-- 1 ed ed 888482 Sep 30 06:48 libip_8.a
  -rw-r--r-- 1 ed ed 854490 Sep 30 06:48 libip_d.a
```

**Comment by GeorgeGayno-NOAA** [comment]
"4" is 4-byte floats/ints; "d" is 8-byte floats/4-byte ints; "8" is 8-byte floats/ints

**Comment by edwardhartnett** [comment]
OK, now I get it. ;-) Similar to https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/226

**Comment by edwardhartnett** [comment]
We need to end this practice, so we need to build just one of the libraries and let Fortran match the types.

I'm not sure what effect this will have on using applications...

**Comment by edwardhartnett** [comment]
OK, this is harder than I thought. See discussion in NOAA-EMC/NCEPLIBS-sp#76.

We will table this idea for now. I will close this issue.
