### ISSUE TITLE
compiling libip_4.so for grib2io-interp

### ISSUE THREAD

**Issue by deadpickle** [NOAA-EMC/NCEPLIBS-ip#259]
Trying to install grib2io-interp so i built NCEPLIBS-ip from source. It produced libip_4.a but not the shared library that grib2io_interp requires. How can I get the build to generate the shared libraries.

**Comment by AlexanderRichert-NOAA** [comment]
By default only the static library is built. To enable the shared library: `cmake -DBUILD_SHARED_LIBS=ON`
