### ISSUE TITLE
CMake build needs to require sp library

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#27]
In the workflow we have:

```
    - name: checkout-sp
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-sp
        path: sp
        ref: develop

    - name: build-sp
      run: |
        cd sp
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/sp
        make -j2
        make install


```   

Yet CMakeLists.txt does not check for sp, and it is not needed to build ip.

**Comment by kgerheiser** [comment]
The thing is that none of these libraries have interfaces and they are built statically so even though it does use sp it's not enforced at compile time.

**Comment by edwardhartnett** [comment]
OK, so then the bug here is that the ip CMakeLists.txt file does not require sp, but should.

**Comment by edwardhartnett** [comment]
OK, actually the sp library is required in the CMake build, but only if tests are run. Here's the tests/CMakeLists.txt file:

```
#list(APPEND CMAKE_CTEST_ARGUMENTS "--output-on-failure")

file(COPY data/ DESTINATION data)

find_package(sp REQUIRED)

add_pfunit_ctest (interp_test
  TEST_SOURCES test_mod.pf
  LINK_LIBRARIES ip::ip_4 sp::sp_4
)

```

Is sp only needed for testing?

**Comment by kgerheiser** [comment]
SP is needed to create an executable that uses ip because of the aforementioned interface/static library thing. It should be found at compile time even if it's currently not used.

**Comment by edwardhartnett** [comment]
OK, understood. In that case this should be checked at the top level CMakeLists.txt file.

When you execute https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/226, then sp will be needed for make all as well as make tests, because the interface will allow fortran to check for sp at compile time. (I believe...)

**Comment by kgerheiser** [comment]
That is correct
