### ISSUE TITLE
Rename gdswzd_c.F90 to gdswzd_c.f90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#29]
gdswzd_c.F90 is the only file with an "F90" extension. The rest have "f90".

The reason to use F90 is if we want pre-processing with the C pre-processor, which all modern Fortran compilers support (as far as a I know).

But we are not using any pre-processing symbols in gdswzd_c.F90 so it should use the same extension as all the other files.

**Comment by kgerheiser** [comment]
It uses the pre-processor

https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/f02ddf2502b6bdbf1fd3342d6d7bd64eef102307/src/gdswzd_c.F90#L62

**Comment by edwardhartnett** [comment]
OK, we'll leave the issue of filenames for this round of refactoring...
