### ISSUE TITLE
NCEP authors list is a 404 error...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#32]
We have the following in the README:

### Authors

* **[NCEP/EMC](NCEP.List.EMC.nceplibs.Developers@noaa.gov)**

This gives us a link in the README, but when I click on the link I get a 404 not found error. ;-)

What is this supposed to be pointing to?

**Comment by kgerheiser** [comment]
This isn't there anymore.
