### ISSUE TITLE
clean up legacy testing directories and code

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#33]
We have some legacy testing here that needs to be modernized.

There is a tests directory, with two subdirectories, unit_test and unit_test_for_c.

In unit_test_for_c there are two subdirectories, sorc and scripts. The sorc directory contains the test code, the scripts directory some scripts to run the tests. (At least oneof the scripts would not run because it has merge artivacts in in...).

OK, the answer here is to remove move the test codes up one level, and remove the sorc and scripts directories. As far as I can see there should be no need for scripts to run tests in any case, this is a library and can be tested directly from code, which can be run directly from CMake. No need for a script.

(But when I did this I discovered that a header file is missing, iplib.h, and the tests don't build. See #34 )

For the unit_test directory we have even more complexity. There is a sorc directory with scalar and vector subdirectories. There is an autoconf build system, but just for the tests in unit_test. Within scalar and vector are some Fortran test codes. There is also a scripts directory.

The answer here is going to be once again remove all the scripts, which we don't need, and remove the autoconf build system, eliminate the sorc and scripts subdirectories and move all the fortran test code up to the unit_test directory, changing the file names to distinguish between the vector and scalar tests.

**Comment by kgerheiser** [comment]
Fixed with #41
