### ISSUE TITLE
Test in unit_test_for_c requires missing iplib.h

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#34]
When I try to build the test in unit_test_for_c, it fails because it can't find iplib.h. There is no iplib.h in the project. ;-)

So where is it supposed to come from?

```
/home/ed/NCEPLIBS-ip/tests/unit_test_for_c/test_gdswzd_4.c:4:10: fatal error: iplib.h: No such file or directory
    4 | #include "iplib.h"
      |          ^~~~~~~~~
compilation terminated.


```

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett I discovered the same thing when creating the v3.0.2 tag.  Get them here: 
https://github.com/NOAA-EMC/NCEPLIBS-ip/releases/tag/ip_v3.0.2

**Comment by edwardhartnett** [comment]
What is the plan for merging this back to the develop branch?

**Comment by GeorgeGayno-NOAA** [comment]
> What is the plan for merging this back to the develop branch?

Those files will need to be recovered from the tag, then added back to develop.  I don't know if they should reside in the source code directory or in a separate directory.

**Comment by edwardhartnett** [comment]
You said that files had to be recovered from this tag? What other files besides iplib.h? Why does this tagged release contain files not in develop?

**Comment by GeorgeGayno-NOAA** [comment]
> You said that files had to be recovered from this tag? What other files besides iplib.h? Why does this tagged release contain files not in develop?

Because we have been very sloppy with our NCEPLIBS development lately.  The missing include files would have been caught by the "unit tests for c" test.  But all the regression and unit tests no longer work ever since the autotools-based build was removed (several months ago).   I spent a lot of time creating those tests and I hope you can get them working again.  You will need them when combining IP and IP2.

**Comment by edwardhartnett** [comment]
What specific files are missing?

**Comment by GeorgeGayno-NOAA** [comment]
> What specific files are missing?

The missing include files are:  iplib_4.h, iplib_d.h and iplib_8.h

**Comment by edwardhartnett** [comment]
Is there anything else different in the tagged branch? Or just the header files?

**Comment by GeorgeGayno-NOAA** [comment]
> Is there anything else different in the tagged branch? Or just the header files?

I am not sure.  I would do a diff of the source files.
