### ISSUE TITLE
Merge in code from ip2?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#38]
See https://github.com/NOAA-EMC/NCEPLIBS/issues/122

**Comment by edwardhartnett** [comment]
@kgerheiser closing this as it has been done.

**Comment by edwardhartnett** [comment]
@kgerheiser was this actually done or was I wrong to close this issue?

**Comment by edwardhartnett** [comment]
@kgerheiser what's the status of this work?

**Comment by kgerheiser** [comment]
I have a PR ready

**Comment by edwardhartnett** [comment]
Well this is a hell of a giant PR!

In future, try and put up smaller PRs so we have a hope of giving a good review.

**Comment by kgerheiser** [comment]
I agree, but part of the reason for this is that the original code history came from NCEPLIBS-ip2, but we don't want to keep ip2 around, so this is basically re-writing history coming into ip.

**Comment by kgerheiser** [comment]
This has been completed.

**Comment by edwardhartnett** [comment]
It's not clear if this work is complete... @kgerheiser is it? Can users now use an ip library release, and get rid of any ip2 releases?
