### ISSUE TITLE
Identify areas for test improvement

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#44]
We need to run code coverage analysis for this library.

copybg is a utility that will be useful in testing. 

Some reg_tests were in the repo but have been lost. They can be recovered. Kyle will recover these.

**Comment by kgerheiser** [comment]
We've got code coverage going and we're sitting at 66% coverage.

https://github.com/NOAA-EMC/NCEPLIBS-ip/actions/workflows/gcc-docs-coverage.yml

**Comment by edwardhartnett** [comment]
Awesome progress. I will close this issue.
