### ISSUE TITLE
Recover reg_test tests

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-ip#46]
These tests were deleted, but are still in the history. Recover them and convert them to CMake.

**Comment by AlexanderRichert-NOAA** [comment]
The reg_tests I can find in v3.0.1 are either already implemented as unit tests in the current version or test obsolete functions. The exception is some of the copygb tests, which should be implemented under grib_util then tested through the Spack CI (see https://github.com/NOAA-EMC/NCEPLIBS-grib_util/issues/116#issuecomment-1730043592). Also creating https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/201 to add testing with bitmap filtering (which is present in the old reg_tests for ipolates/ipolatev but not the current unit tests for those functions).
