### ISSUE TITLE
automate test coverage measurment

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#53]
We need this on all projects, and this is a simple one to start with.

We need some method of automatically running code coverage analysis on GitHub actions. In this way, all developers will easily be able to tell what code is untested.

**Comment by kgerheiser** [comment]
We have this https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/develop/.github/workflows/gcc-docs-coverage.yml
