### ISSUE TITLE
Add Doxygen to ip_grid_descriptor.f90

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-ip#57]

**Comment by edwardhartnett** [comment]
You can add one issue: Fix doxygen throughout repo, and then keep referring to it, instead of a separate issue for each file.

**Comment by kgerheiser** [comment]
Ok, I thought you might want specific issues.

**Comment by edwardhartnett** [comment]
That would be too many! ;-)
