### ISSUE TITLE
Support NCEP rotated grids in grib2

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-ip#70]
The ip2 library doesn't support NCEP rotated grids (32768, 32769).

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-32768.shtml

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-32769.shtml

Two builds of wgrib2 are required (one built with ip and one built with ip2) to support all features. It would be nice to offer all in one.

@GeorgeGayno-NOAA do you know how this would be implemented?

**Comment by GeorgeGayno-NOAA** [comment]
IP2 supports rotated lat/lon grids following the official WMO template: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-1.shtml

But IP2 does not support the local NCEP templates that describe rotated lat/lon grids.

Is anyone using the local NCEP templates?

**Comment by kgerheiser** [comment]
Yes, it has come up several times before.

**Comment by GeorgeGayno-NOAA** [comment]
That is too bad. 

The easiest way to handle this is to add a routine to convert the template elements to this module:
https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/develop/src/ip_rot_equid_cylind_grid_mod.f90#L31

You likely already have the routine you need in that module.  Note how the grib1 definition and the local NCEP grib2 definition have the same essential elements. I suspect the local NCEP grid2 definition was directly lifted from the grib1 definition:
https://www.nco.ncep.noaa.gov/pmb/docs/on388/tabled.html (See templates halfway down the page).
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-32769.shtml

**Comment by kgerheiser** [comment]
Thanks

I think I figured out for the most part. Just need to make sure units are correct and test it out.

https://github.com/kgerheiser/NCEPLIBS-ip/blob/d1d7d8f88939a3a2cfd299a795cd9361d7aee7c6/src/ip_rot_equid_cylind_egrid_mod.f90#L199

I was able to see how wgrib2 handled creating a grib1 descriptor to pass to ip for those grids and work backwards:

https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/blob/develop/wgrib2/mk_kgds.c#L193

**Comment by kgerheiser** [comment]
@GeorgeGayno-NOAA any idea why 90 degrees is added to `RLAT0` in grib2, but not in grib1?

https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/c8f29ed25cb1a2635e5bcc1cb262b771c1c8498c/src/ip_rot_equid_cylind_grid_mod.f90#L114

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA any idea why 90 degrees is added to `RLAT0` in grib2, but not in grib1?
> 
> https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/c8f29ed25cb1a2635e5bcc1cb262b771c1c8498c/src/ip_rot_equid_cylind_grid_mod.f90#L114

GRIB2 defines the grid rotation according to the lat/lon of the southern pole of projection. GRIB1 and the GRIB2 local template use the actual lat/lon. See the Note 2 here:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-1.shtml

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA this work was apparently not completed. Do you have any idea whether this change is still needed, and, if so, how urgently?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA this work was apparently not completed. Do you have any idea whether this change is still needed, and, if so, how urgently?

I have not received any inquiries about this. Since it was opened 18 months ago, I suspect this is not urgent (or the person found a workaround).
