### ISSUE TITLE
release 4.0.0

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#76]
The ip library has changed and absorbed the ip2 library. It's time for a release.

Should the next release be called ip-4.0.0 since it represents an important change in the API?

**Comment by kgerheiser** [comment]
I will create a 4.0.0 release.

The API doesn't technically change, but it will break code that doesn't use `ip_mod`, and without interface checks by the compiler I've seen some calls that play loose with the type/rank passed to these routines.

**Comment by edwardhartnett** [comment]
OK does the 4.0.0 release do away with the "_4" and "_d" on the library names and just build one library for all types?

**Comment by kgerheiser** [comment]
No, it still builds the different libraries. 

There's really no good way to do it with Fortran. You always end up with some hack using the pre-processor or lots of duplicate code. I think the answer might be to work solely on real64 internally, and if a real32 interface is necessary add one that just promotes real32 to real64 and call the internal real64 functions.

**Comment by edwardhartnett** [comment]
OK, can we have this soon so I can adjust the grib libraries to use the new combined ip library?

Don't forget to mention in the release notes that this includes the ip2 library...

**Comment by kgerheiser** [comment]
On it

**Comment by kgerheiser** [comment]
Done

**Comment by edwardhartnett** [comment]
Dont forget to update the spack repo with the new release.

**Comment by edwardhartnett** [comment]
You also need to update the docs on the gh-pages branch.

Also modify the README to point to the docs in the gh-pages branch, as all the other READMEs do.

Also, also modify the README in the ip2 package to say it is deprecated and that users should look for the ip package instead...

**Comment by kgerheiser** [comment]
Updated gh-pages and Spack.

I think there's an automated way to update documentation with a Github Action. Something like 

```
on: publish
run: |
    <create doxygen docs>
   git push gh-pages
```

**Comment by edwardhartnett** [comment]
@kgerheiser that gh-pages automatic update on release would be a great thing to figure out.

But remember, we only want to update when we do a release, not every time the code changes...

**Comment by edwardhartnett** [comment]
OK, this version was released, so I will close this issue. Thanks @kgerheiser for all the hard work.
