### ISSUE TITLE
can't get grib_util to build with ip-4.0.0

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#80]
I have been trying to get grib_util to build with ip-4.0.0, but no luck.

In the CMakeLists.txt I added:

```
# For NCEPLIBS-ip-4.0.0 and later, we need to add a "use" statement to
# the code. Check for this...
if(ip_VERSION GREATER_EQUAL 4.0.0)
  add_compile_definitions(USE_IP_MOD)
  message(STATUS "ip library > 4.0.0, USE_IP_MOD set")
else()
  message(STATUS "ip library < 4.0.0, USE_IP_MOD not set")
endif()
```

And this seems to work, when compiling with ip-4.0.0 I see:

`cd /home/ed/NCEPLIBS-grib_util/b/src/copygb && /usr/bin/gfortran -DUSE_IP_MOD -I/usr/local/NCEPLIBS-bacio-2.5.0/include -I/usr/local/NCEPLIBS-w3emc-2.9.2/include_d -I/usr/local/NCEPLIBS-ip-4.0.0/include_d -I/usr/local/NCEPLIBS-sp-2.3.3/include_d -g -fdefault-real-8  -O3 -g -fdefault-real-8  -c /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F -o CMakeFiles/copygb.dir/copygb.F.o
`

So the USE_IP_MOD pre-processor define is being properly set.

In the code I have:

```
      PROGRAM COPYGB
#ifdef USE_IP_MOD
      use ip_mod
#endif

```

But when I try to build:

```
cd /home/ed/NCEPLIBS-grib_util/b/src/copygb && /snap/cmake/1000/bin/cmake -E cmake_link_script CMakeFiles/copygb.dir/link.txt --verbose=1
/usr/bin/gfortran -g -fdefault-real-8  -O3 -g -fdefault-real-8  CMakeFiles/copygb.dir/copygb.F.o -o copygb  /usr/local/NCEPLIBS-bacio-2.5.0/lib/libbacio.a /usr/local/NCEPLIBS-w3emc-2.9.2/lib/libw3emc_d.a /usr/local/NCEPLIBS-ip-4.0.0/lib/libip_d.a /usr/local/NCEPLIBS-sp-2.3.3/lib/libsp_d.a /usr/local/NCEPLIBS-bacio-2.5.0/lib/libbacio.a 
/usr/bin/ld: CMakeFiles/copygb.dir/copygb.F.o: in function `intgrib1_':
/home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1225: undefined reference to `ipolates_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1300: undefined reference to `ipolatev_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1331: undefined reference to `ipolatev_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1290: undefined reference to `ipolatev_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1231: undefined reference to `ipolates_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1268: undefined reference to `ipolatev_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1253: undefined reference to `ipolates_'
/usr/bin/ld: /home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:1212: undefined reference to `ipolates_'
/usr/bin/ld: CMakeFiles/copygb.dir/copygb.F.o: in function `MAIN__':
/home/ed/NCEPLIBS-grib_util/src/copygb/copygb.F:260: undefined reference to `makgds_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/copygb/CMakeFiles/copygb.dir/build.make:101: src/copygb/copygb] Error 1
make[2]: Leaving directory '/home/ed/NCEPLIBS-grib_util/b'
make[1]: *** [CMakeFiles/Makefile2:1075: src/copygb/CMakeFiles/copygb.dir/all] Error 2
make[1]: Leaving directory '/home/ed/NCEPLIBS-grib_util/b'
make: *** [Makefile:146: all] Error 2

```

What am I doing wrong?

There is a branch in grib_util called ejh_ip which has all these changes...

**Comment by kgerheiser** [comment]
I'll take a look

**Comment by kgerheiser** [comment]
It's because grib_util plays loose with the type/kind/rank checking. It passes a scalar value to ip when the actual dummy argument is an array.

**Comment by edwardhartnett** [comment]
OK, well others might do the same. Can you add something to ip to handle this?

**Comment by kgerheiser** [comment]
The fix is to update the grib_util code so that the arguments match. I can put in a PR.

**Comment by edwardhartnett** [comment]
Yes, but then if any other programs have done this same thing, they also will need to be fixed.

Can't you add a function to the ip interface that takes a scalar? Then, if other programs also do this with a scalar, it will automatically work...

**Comment by kgerheiser** [comment]
Ok, I was able to do that for ipolates/ipolatev. Figuring out the makegds  thing now.

I think the fix is fine here for one variable (ibi/ibo), but hopefully other variables aren't abused in the same way because it will quickly increase the number of interfaces.

**Comment by kgerheiser** [comment]
Fixing a similar issue in copygb2 which passes a 1d array to a 2d argument
