### ISSUE TITLE
Remove warning about supported compilers...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#83]
We don't need to warn about supported compilers. This is standard fortran and will compile on any Fortran compiler.

**Comment by kgerheiser** [comment]
It's not standard Fortran in regards to compile flags. The 4, 8, d versions still exist.

**Comment by edwardhartnett** [comment]
Do we have a version of ip that does not need 4.8.d builds yet?

**Comment by edwardhartnett** [comment]
OK, we will leave the warning and I will close this issue.
