### ISSUE TITLE
Combine the NCEPLIBS-sp code with this repo

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#93]
Should we combine NCEPLIBS-sp into NCEPLIBS-ip? This would eliminate a package and a dependency for many other packages.

Does anyone use sp without ip?

@kgerheiser and @GeorgeGayno-NOAA your opinion would be welcome.

**Comment by GeorgeGayno-NOAA** [comment]
There are likely some users of sp only. But as the FV3 dynamic core replaces the old GFS spectral core throughout EMC, I would expect the number sp only users will decrease. Whereas ip will continue to be widely used for the foreseeable future.  Does that help?

**Comment by kgerheiser** [comment]
Agreed with @GeorgeGayno-NOAA. A better approach would be to deprecate spectral interpolation part of ip and eventually the entire sp library once it's not needed.

**Comment by edwardhartnett** [comment]
OK, we will proceed with the plan suggested above by @GeorgeGayno-NOAA and @kgerheiser after completing #40.

**Comment by edwardhartnett** [comment]
I'm reopening this issue due to the discovery that we actually need splat_ from the sp library.

So it is proposed (by @GeorgeGayno-NOAA see #99 ) that we take just the necessary functions from sp.

Which leads to the question which of the following can we deprecate? Which of these is not used with UFS:

```
  use ip_equid_cylind_grid_mod
  use ip_gaussian_grid_mod
  use ip_lambert_conf_grid_mod
  use ip_polar_stereo_grid_mod
  use ip_rot_equid_cylind_grid_mod
  use ip_rot_equid_cylind_egrid_mod
  use ip_mercator_grid_mod
  use ip_station_points_grid_mod
  use ip_grid_mod

```

@GeorgeGayno-NOAA do you know? Or is this the wrong way to approach the problem? When the ip library can be separate from the sp library, does it mean that some of these grid_mod files can be deprecated (i.e. not built as part of a standalone ip library?)

**Comment by GeorgeGayno-NOAA** [comment]
> I'm reopening this issue due to the discovery that we actually need splat_ from the sp library.
> 
> So it is proposed (by @GeorgeGayno-NOAA see #99 ) that we take just the necessary functions from sp.
> 
> Which leads to the question which of the following can we deprecate? Which of these is not used with UFS:
> 
> ```
>   use ip_equid_cylind_grid_mod
>   use ip_gaussian_grid_mod
>   use ip_lambert_conf_grid_mod
>   use ip_polar_stereo_grid_mod
>   use ip_rot_equid_cylind_grid_mod
>   use ip_rot_equid_cylind_egrid_mod
>   use ip_mercator_grid_mod
>   use ip_station_points_grid_mod
>   use ip_grid_mod
> ```
> 
> @GeorgeGayno-NOAA do you know? Or is this the wrong way to approach the problem? When the ip library can be separate from the sp library, does it mean that some of these grid_mod files can be deprecated (i.e. not built as part of a standalone ip library?)

In your list, the spectral library is only required for "ip_gaussian_grid_mod", so the others will not need to be deprecated. The global FV3 outputs data on the gaussian grid, so "ip_gaussian_grid.mod" must be retained to geo-locate these grids.

Separately, the spectral library is also used for spectral interpolation. (See https://github.com/NOAA-EMC/NCEPLIBS-ip/blob/develop/src/spectral_interp_mod.F90). In that module, I see calls to "SPTRUNS", "SPTRUNG" and other SPLIB routines. Spectral-based interpolation can be used with grids other than gaussian. So, if you survey EMC and determine that spectral interpolation is not used, you can remove "spectral_interp_mod.F90". Then you would only need to retain the SPLIB routines needed by "ip_gaussian_grid.mod".

**Comment by edwardhartnett** [comment]
OK thanks for the info.

I'm not sure what the right thing to do is...

**Comment by edwardhartnett** [comment]
Let me fully explain this idea: we create subdirectories called sp and sp_test and move the sp code there. Then, starting with the next release of the ip library, the sp library is no longer required to build UFS.

If we take part of the sp and leaving the rest we would need to release a new sp library version and a new ip library version.

If we just move the whole sp library into ip, then we don't need to do any further releases of the sp library.

Then, over time, if some of the code in the sp subdirectory can be shown to be unneeded, it can be removed. More likely it will just be abandoned in place. 

The reasoning is that there are probably very few users who use sp without also using ip, so bundling them together would reduce our overall maintenance burden without much effort.

**Comment by edwardhartnett** [comment]
As I continue to work on CI systems, spack, and other ways of building our software, I see again and again that we have way too many repos for the code we have. THere's no reason to scatter our code across so many repos - it only makes extra work.

I cannot see any good reason that sp should not be combined into ip. Then there will be one repo, ip, where we used to have three, sp, ip, and ip2.

The only reason not to do this is if there is a large and important community of users who only use sp. But there is not.

**Comment by GeorgeGayno-NOAA** [comment]
I opened an issue to remove the SPLIB dependency from UFS_UTILS: 
https://github.com/ufs-community/UFS_UTILS/issues/886

I can't completely eliminate this dependency. SPLIB routine `splat` will need to be retained to geo-reference global gaussian grids. These gaussian grids are widely used in current OPS.

**Comment by edwardhartnett** [comment]
OK, so we do need to keep the sp code.

So let us proceed to move the sp code into the ip repo. As the sp code is retired, we can remove it from ip, but let's move it to ip now and get rid of the sp dependency everywhere.

**Comment by GeorgeGayno-NOAA** [comment]
> OK, so we do need to keep the sp code.
> 
> So let us proceed to move the sp code into the ip repo. As the sp code is retired, we can remove it from ip, but let's move it to ip now and get rid of the sp dependency everywhere.

The `splat` function looks well contained (calls a couple routines). So, you may be able to retain it while getting rid of most of the SPLIB code. Can you create a test version of IPLIB that only contains the `splat` function?

**Comment by AlexanderRichert-NOAA** [comment]
Yes I can try that in the next little while. Based on looking at some of the operational code a little while back, I think there are some other pieces we'll need to keep, but I'll make a copy of my merged sp/ip code that just has splat and we can go from there.

**Comment by GeorgeGayno-NOAA** [comment]
> Yes I can try that in the next little while. Based on looking at some of the operational code a little while back, I think there are some other pieces we'll need to keep, but I'll make a copy of my merged sp/ip code that just has splat and we can go from there.

As a test, I was able to remove the SPLIB dependency from a small program by making routines `splat` and `lapack_gen` local to the program: https://github.com/ufs-community/UFS_UTILS/issues/886#issuecomment-1899087042

**Comment by GeorgeGayno-NOAA** [comment]
> Yes I can try that in the next little while. Based on looking at some of the operational code a little while back, I think there are some other pieces we'll need to keep, but I'll make a copy of my merged sp/ip code that just has splat and we can go from there.

If you really want to get rid of SPLIB, you will need to deprecate the spectral interpolation method from IPLIB. I suspect that method is not very popular. Most people use 'bilinear', 'neighbor' and 'budget'. You could always do a survey of EMC to verify.

**Comment by edwardhartnett** [comment]
OK, I think the easiest way forward is to move the existing sp code to ip. 

Then, if people can remove the use of the code everywhere, and we can delete it from ip, great. But I am somewhat skeptical. Every time we look into this we find some things in sp we need to keep.

**Comment by AlexanderRichert-NOAA** [comment]
Please see & comment on #210, and let me know your thoughts on the first bullet point, namely, for the next version, keep sp routines accessible as they currently are as opposed to through a module, in the hope that developers can update ip,  and disable sp and have everything good to go without further code changes.

**Comment by edwardhartnett** [comment]
Yes, looks fantastic. Terrific!!
