### ISSUE TITLE
Fill in documentation fields with "???"

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#97]
In eliminating doxygen warnings, I used "???" when I didn't know what to write.

These need to be filled in.

For a starting point, from ip_mercator_grid_mod.f90:
```
  type, extends(ip_grid) :: ip_mercator_grid
     real :: rlat1 !< ???
     real :: rlon1 !< ???
     real :: rlon2 !< ???
     real :: rlati !< ???
     real :: hi !< ???
     real :: dlon !< ???
     real :: dphi !< ???

```

@GeorgeGayno-NOAA and @kgerheiser do you know what these should say?

**Comment by GeorgeGayno-NOAA** [comment]
rlat1 - Latitude of first grid point. Section 3, octets 39-42.
rlon1 - Longitude of first grid point. Section 3, octets 43-46.
rlon2 - Longitude of last grid point. Section 3, octets 56-59.
rlati - Latitude at which the Mercator projection intersects the Earth. Section 3, octets 48-51.
hi -Scan mode in the 'i' direction. Section 3, octet 60.
dlon - Longitudinal direction grid length. Section 3, octets 65-68.
dphi - Latitudinal direction grid length. Section 3, octets 69-72.

Do we reference the GRIB2 standard anywhere in the code or on the wiki page? You might want to add a reference about "See GRIB2 template 3.1.0 for more details on Mercator grids."

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-10.shtml

**Comment by edwardhartnett** [comment]
Great I will add this documentation and reference the grib2 pages.

**Comment by edwardhartnett** [comment]
Also from ip_mercator_grid_mod.f90:

@GeorgeGayno-NOAA what are these?

```
  REAL :: DLON !< ???
  REAL :: DPHI !< ???
  REAL :: RERTH !< ???

```

**Comment by edwardhartnett** [comment]
More questions - from ip_rot_equid_cylind_egrid_mod.f90:

     real(kd) :: rlon0 !< ???
     real(kd) :: rlon1 !< ???
     real(kd) :: rlat1 !< ???
     real(kd) :: clat0 !< ???
     real(kd) :: slat0 !< ???
     real(kd) :: dlats !< ???
     real(kd) :: dlons !< ???
     real(kd) :: hi !< ???
     integer :: irot !< ???

Are the variables with the same name the same meaning as ip_mercator_grid_mod.f90?

**Comment by GeorgeGayno-NOAA** [comment]
> Also from ip_mercator_grid_mod.f90:
> 
> @GeorgeGayno-NOAA what are these?
> 
> ```
>   REAL :: DLON !< ???
>   REAL :: DPHI !< ???
>   REAL :: RERTH !< ???
> ```

DLON - Longitudinal direction grid length.
DPHI - Latitudinal direction grid length.
RERTH - Radius of the earth

**Comment by GeorgeGayno-NOAA** [comment]
> More questions - from ip_rot_equid_cylind_egrid_mod.f90:
> 
> ```
>  real(kd) :: rlon0 !< ???
>  real(kd) :: rlon1 !< ???
>  real(kd) :: rlat1 !< ???
>  real(kd) :: clat0 !< ???
>  real(kd) :: slat0 !< ???
>  real(kd) :: dlats !< ???
>  real(kd) :: dlons !< ???
>  real(kd) :: hi !< ???
>  integer :: irot !< ???
> ```
> 
> Are the variables with the same name the same meaning as ip_mercator_grid_mod.f90?

rlon0 - Longitude of southern pole of projection.
rlon1 - Longitude of first grid point.
rlat1 - Latitude of first grid point.
clat0 - Cosine of the latitude of the southern pole of projection.
slat0 - Sine of the latitude of the southern pole of projection.
dlats - 'J'-direction grid increment.
dlons - 'I'-direction grid increment.
hi - Scan mode in the 'i' direction.
irot - Rotation flag. When '0' the u/v vector components are relative to north/east. When '1' the u/v vector components are grid relative.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA in ip_rot_equid_cylind_grid_mod.F90 we have:

```
  type, extends(ip_grid) :: ip_rot_equid_cylind_grid
     real(kd) :: clat0 !< ???
     real(kd) :: dlats !< ???
     real(kd) :: dlons !< ???
     real(kd) :: rlon0 !< ???
     real(kd) :: slat0 !< ???
     real(kd) :: wbd !< ???
     real(kd) :: sbd !< ???
     integer :: irot !< ???

```

Would these be the same as the same-named ones in ip_rot_equid_cylind_egrid_mod.F90?

 ```
 type, extends(ip_grid) :: ip_rot_equid_cylind_egrid
     real(kd) :: rlon0 !< Longitude of southern pole of projection.
     real(kd) :: rlon1 !< Longitude of first grid point.
     real(kd) :: rlat1 !< Latitude of first grid point.
     real(kd) :: clat0 !< Cosine of the latitude of the southern pole of projection.
     real(kd) :: slat0 !< Sine of the latitude of the southern pole of projection.
     real(kd) :: dlats !< 'J'-direction grid increment.
     real(kd) :: dlons !< 'I'-direction grid increment.
     real(kd) :: hi !< Scan mode in the 'i' direction.
     integer :: irot !< Rotation flag. When '0' the u/v vector components are relative to north/east. When '1' the u/v vector components are grid relative.

```

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA in ip_rot_equid_cylind_grid_mod.F90 we have:
> 
> ```
>   type, extends(ip_grid) :: ip_rot_equid_cylind_grid
>      real(kd) :: clat0 !< ???
>      real(kd) :: dlats !< ???
>      real(kd) :: dlons !< ???
>      real(kd) :: rlon0 !< ???
>      real(kd) :: slat0 !< ???
>      real(kd) :: wbd !< ???
>      real(kd) :: sbd !< ???
>      integer :: irot !< ???
> ```
> 
> Would these be the same as the same-named ones in ip_rot_equid_cylind_egrid_mod.F90?
> 
> ```
> type, extends(ip_grid) :: ip_rot_equid_cylind_egrid
>     real(kd) :: rlon0 !< Longitude of southern pole of projection.
>     real(kd) :: rlon1 !< Longitude of first grid point.
>     real(kd) :: rlat1 !< Latitude of first grid point.
>     real(kd) :: clat0 !< Cosine of the latitude of the southern pole of projection.
>     real(kd) :: slat0 !< Sine of the latitude of the southern pole of projection.
>     real(kd) :: dlats !< 'J'-direction grid increment.
>     real(kd) :: dlons !< 'I'-direction grid increment.
>     real(kd) :: hi !< Scan mode in the 'i' direction.
>     integer :: irot !< Rotation flag. When '0' the u/v vector components are relative to north/east. When '1' the u/v vector components are grid relative.
> ```

I believe so. Let me check. There are also some new variables that I will define.

**Comment by edwardhartnett** [comment]
Awesome. We are going to do a release soon so it would be great if we could get all these ??? filled in. There are not very many left.

**Comment by GeorgeGayno-NOAA** [comment]
The definitions are the same for clat0, dlats, dlons, rlon0, slat0 and irot.

WBD - Longitude of the western boundary of the grid before rotation.
SBD - Latitude of the southern boundary of the grid before rotation.

**Comment by edwardhartnett** [comment]
OK, excellent. Here's the next question:

In both  ip_rot_equid_cylind_grid_mod.F90 and  ip_rot_equid_cylind_egrid_mod.F90 there is another set of variables, in upper case, below the module variables, with the same names. Would they have the same documentation too? What are they all about?

Here's one of the files for example:

```
  type, extends(ip_grid) :: ip_rot_equid_cylind_grid
     real(kd) :: clat0 !< Cosine of the latitude of the southern pole of projection.
     real(kd) :: dlats !< 'J'-direction grid increment.
     real(kd) :: dlons !< 'I'-direction grid increment.
     real(kd) :: rlon0 !< Longitude of southern pole of projection.
     real(kd) :: slat0 !< Sine of the latitude of the southern pole of projection.
     real(kd) :: wbd !< Longitude of the western boundary of the grid before rotation.
     real(kd) :: sbd !<  Latitude of the southern boundary of the grid before rotation.
     !> Rotation flag. When '0' the u/v vector components are relative
     !> to north/east. When '1' the u/v vector components are grid
     !> relative.
     integer :: irot
   contains
     !> Initializes a Rotated equidistant cylindrical grid given a
     !> grib1_descriptor object. @return N/A
     procedure :: init_grib1
     !> Initializes a Rotated equidistant cylindrical given a
     !> grib2_descriptor object. @return N/A
     procedure :: init_grib2
     !> Calculates Earth coordinates (iopt = 1) or grid coorindates (iopt = -1)
     !> for Gaussian grids. @return N/A
     procedure :: gdswzd => gdswzd_rot_equid_cylind !< ??? @return N/A
  end type ip_rot_equid_cylind_grid

  INTEGER :: IROT !< ???
  REAL(KIND=KD) :: RERTH !< ???
  REAL(KIND=KD) :: CLAT0 !< ???
  REAL(KIND=KD) :: DLATS !< ???
  REAL(KIND=KD) :: DLONS !< ???
  REAL(KIND=KD) :: RLON0 !< ???
  REAL(KIND=KD) :: SLAT0 !< ???

```
What is the relationship between irot and IROT, for example?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, excellent. Here's the next question:
> 
> In both ip_rot_equid_cylind_grid_mod.F90 and ip_rot_equid_cylind_egrid_mod.F90 there is another set of variables, in upper case, below the module variables, with the same names. Would they have the same documentation too? What are they all about?
> 
> Here's one of the files for example:
> 
> ```
>   type, extends(ip_grid) :: ip_rot_equid_cylind_grid
>      real(kd) :: clat0 !< Cosine of the latitude of the southern pole of projection.
>      real(kd) :: dlats !< 'J'-direction grid increment.
>      real(kd) :: dlons !< 'I'-direction grid increment.
>      real(kd) :: rlon0 !< Longitude of southern pole of projection.
>      real(kd) :: slat0 !< Sine of the latitude of the southern pole of projection.
>      real(kd) :: wbd !< Longitude of the western boundary of the grid before rotation.
>      real(kd) :: sbd !<  Latitude of the southern boundary of the grid before rotation.
>      !> Rotation flag. When '0' the u/v vector components are relative
>      !> to north/east. When '1' the u/v vector components are grid
>      !> relative.
>      integer :: irot
>    contains
>      !> Initializes a Rotated equidistant cylindrical grid given a
>      !> grib1_descriptor object. @return N/A
>      procedure :: init_grib1
>      !> Initializes a Rotated equidistant cylindrical given a
>      !> grib2_descriptor object. @return N/A
>      procedure :: init_grib2
>      !> Calculates Earth coordinates (iopt = 1) or grid coorindates (iopt = -1)
>      !> for Gaussian grids. @return N/A
>      procedure :: gdswzd => gdswzd_rot_equid_cylind !< ??? @return N/A
>   end type ip_rot_equid_cylind_grid
> 
>   INTEGER :: IROT !< ???
>   REAL(KIND=KD) :: RERTH !< ???
>   REAL(KIND=KD) :: CLAT0 !< ???
>   REAL(KIND=KD) :: DLATS !< ???
>   REAL(KIND=KD) :: DLONS !< ???
>   REAL(KIND=KD) :: RLON0 !< ???
>   REAL(KIND=KD) :: SLAT0 !< ???
> ```
> 
> What is the relationship between irot and IROT, for example?

IROT (and some of the other variables you list) appears to be a local copy self%irot. The original library code used IROT. I suspect the developer did not want to replace all instances of IROT with self%irot as there is always a chance to add bugs. But that is just my guess.

**Comment by edwardhartnett** [comment]
OK, that filled in most of the rest of those! Here's the last few:

  ```
REAL(KIND=KD) :: CLAT !< ???
  REAL(KIND=KD) :: CLAT0 !< Local copy of clat0.
  REAL(KIND=KD) :: CLATR !< ???
  REAL(KIND=KD) :: CLON !< ???
  REAL(KIND=KD) :: DLATS !< Local copy of dlats.
  REAL(KIND=KD) :: DLONS !< Local copy of dlons.
  REAL(KIND=KD) :: RERTH !< Radius of the Earth.
  REAL(KIND=KD) :: RLON0 !< Local copy of rlon0.
  REAL(KIND=KD) :: SLAT !< ???
  REAL(KIND=KD) :: SLAT0 !< Local copy of slat0.
  REAL(KIND=KD) :: SLATR !< ???

```

Here's some code that sets CLAT and CLON:

```
                CLAT=SQRT(1-SLAT**2)
                CLON=(CLAT0*CLATR*CLONR-SLAT0*SLATR)/CLAT
                CLON=MIN(MAX(CLON,-1._KD),1._KD)

```
Any clue what CLAT and CLON are?

Here's the code that sets SLATR. Any ideas what it is?

```
      SLAT1=SIN(RLAT1/DPR)
      CLAT1=COS(RLAT1/DPR)
      SLAT0=SIN(RLAT0/DPR)
      CLAT0=COS(RLAT0/DPR)
      HS=SIGN(1._KD,MOD(RLON1-RLON0+180+3600,360._KD)-180)
      CLON1=COS((RLON1-RLON0)/DPR)
      SLATR=CLAT0*SLAT1-SLAT0*CLAT1*CLON1

```

**Comment by GeorgeGayno-NOAA** [comment]
> OK, that filled in most of the rest of those! Here's the last few:
> 
> ```
> REAL(KIND=KD) :: CLAT !< ???
> REAL(KIND=KD) :: CLAT0 !< Local copy of clat0.
> REAL(KIND=KD) :: CLATR !< ???
> REAL(KIND=KD) :: CLON !< ???
> REAL(KIND=KD) :: DLATS !< Local copy of dlats.
> REAL(KIND=KD) :: DLONS !< Local copy of dlons.
> REAL(KIND=KD) :: RERTH !< Radius of the Earth.
> REAL(KIND=KD) :: RLON0 !< Local copy of rlon0.
> REAL(KIND=KD) :: SLAT !< ???
> REAL(KIND=KD) :: SLAT0 !< Local copy of slat0.
> REAL(KIND=KD) :: SLATR !< ???
> ```
> 
> Here's some code that sets CLAT and CLON:
> 
> ```
>                 CLAT=SQRT(1-SLAT**2)
>                 CLON=(CLAT0*CLATR*CLONR-SLAT0*SLATR)/CLAT
>                 CLON=MIN(MAX(CLON,-1._KD),1._KD)
> ```
> 
> Any clue what CLAT and CLON are?
> 
> Here's the code that sets SLATR. Any ideas what it is?
> 
> ```
>       SLAT1=SIN(RLAT1/DPR)
>       CLAT1=COS(RLAT1/DPR)
>       SLAT0=SIN(RLAT0/DPR)
>       CLAT0=COS(RLAT0/DPR)
>       HS=SIGN(1._KD,MOD(RLON1-RLON0+180+3600,360._KD)-180)
>       CLON1=COS((RLON1-RLON0)/DPR)
>       SLATR=CLAT0*SLAT1-SLAT0*CLAT1*CLON1
> ```

CLAT is the cosine of the latitude
CLON is the cosine of the difference between rlon and rlon0
SLATR is the sine of the rotated latitude.

They don't have formal names.

**Comment by edwardhartnett** [comment]
OK, great progress!

Now let's turn to file ip_polar_stereo_grid_mod.F90, which has this:

```
  type, extends(ip_grid) :: ip_polar_stereo_grid
     logical :: elliptical !< ???
     real :: rlat1 !< ???
     real :: rlon1 !< ???
     real :: orient !< ???
     real :: h !< ???
     real :: dxs !< ???
     real :: dys !< ???
     real :: slatr !< ???
     integer :: irot !< ???
   contains
     procedure :: init_grib1 !< Initializes a grid given a grib1_descriptor object. @return N/A
     procedure :: init_grib2 !< Initializes a grid given a grib2_descriptor object. @return N/A
     !> Calculates Earth coordinates (iopt = 1) or grid coorindates
     !> (iopt = -1). @return N/A
     procedure :: gdswzd => gdswzd_polar_stereo
  end type ip_polar_stereo_grid

  INTEGER :: IROT !< Local copy of irot.
  REAL :: DE2 !< ???
  REAL :: DXS !< Local copy of dxs.
  REAL :: DYS !< Local copy of dys.
  REAL :: E2 !< ???
  REAL :: RERTH !< Radius of the Earth.
  REAL :: H !< Local copy of h.
  REAL :: ORIENT !< ???
```

Would irot mean the same thing here as in other mods?

Would rlat1 and rlon1 be rotated latitude and longitude?

Would h be the same as in other mods?

**Comment by GeorgeGayno-NOAA** [comment]
> 

Yes, 'irot' is the same variable in the other mods. However, it is stored in a different octet depending on the grid.

**Comment by edwardhartnett** [comment]
OK, what about the others?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, great progress!
> 
> Now let's turn to file ip_polar_stereo_grid_mod.F90, which has this:
> 
> ```
>   type, extends(ip_grid) :: ip_polar_stereo_grid
>      logical :: elliptical !< ???
>      real :: rlat1 !< ???
>      real :: rlon1 !< ???
>      real :: orient !< ???
>      real :: h !< ???
>      real :: dxs !< ???
>      real :: dys !< ???
>      real :: slatr !< ???
>      integer :: irot !< ???
>    contains
>      procedure :: init_grib1 !< Initializes a grid given a grib1_descriptor object. @return N/A
>      procedure :: init_grib2 !< Initializes a grid given a grib2_descriptor object. @return N/A
>      !> Calculates Earth coordinates (iopt = 1) or grid coorindates
>      !> (iopt = -1). @return N/A
>      procedure :: gdswzd => gdswzd_polar_stereo
>   end type ip_polar_stereo_grid
> 
>   INTEGER :: IROT !< Local copy of irot.
>   REAL :: DE2 !< ???
>   REAL :: DXS !< Local copy of dxs.
>   REAL :: DYS !< Local copy of dys.
>   REAL :: E2 !< ???
>   REAL :: RERTH !< Radius of the Earth.
>   REAL :: H !< Local copy of h.
>   REAL :: ORIENT !< ???
> ```
> 
> Would irot mean the same thing here as in other mods?
> 
> Would rlat1 and rlon1 be rotated latitude and longitude?
> 
> Would h be the same as in other mods?

elliptical - When true/false, computations are based on an elliptical/spherical earth.
rlat1 - Latitude of the first grid point.
rlon1 - Longitude of the first grid point.
orient - Orientation longitude.
dxs - 'x'-direction grid length, adjusted by the scanning mode.
dys - 'y'-direction grid length, adjusted by the scanning mode.
slatr - Standard latitude of grid in radians.
h - Hemisphere flag. 0 - NH; 1 - SH
E2- eccentricity of the earth squared.

I need to do some research on what DE2 is.

**Comment by edwardhartnett** [comment]
Well DE2 is DE squared.

But what is DE?

Here's what the program says:
```
    IF (.NOT.ELLIPTICAL) THEN
       DE=(1.+SIN(SLATR))*RERTH

```

**Comment by edwardhartnett** [comment]
THe weird one is E2. It never seems to get set. Is that a bug?

**Comment by GeorgeGayno-NOAA** [comment]
> Well DE2 is DE squared.
> 
> But what is DE?
> 
> Here's what the program says:
> 
> ```
>     IF (.NOT.ELLIPTICAL) THEN
>        DE=(1.+SIN(SLATR))*RERTH
> ```

DE - distance from the pole of projection to the standard latitude.

**Comment by GeorgeGayno-NOAA** [comment]
> THe weird one is E2. It never seems to get set. Is that a bug?

It is set here:
    
```
    DYS=self%dys

    rerth = self%rerth
    e2 = self%eccen_squared
    !
    ! FIND X/Y OF POLE
```

**Comment by edwardhartnett** [comment]
OK, I've set all those and merged to develop.

Moving on to spectral_interp_mod.F90:

```
  !> Interpolate spectral scalar.
  !>
  !> @param ipopt ???
  !> @param grid_in ???
  !> @param grid_out ???
  !> @param MI ???
  !> @param MO ???
  !> @param KM ???
  !> @param IBI ???
  !> @param GI ???
  !> @param NO ???
  !> @param RLAT ???
  !> @param RLON ???
  !> @param IBO ???
  !> @param LO ???
  !> @param GO ???
  !> @param IRET ???
  !>
  !! @author Mark Iredell @date 96-04-10
  subroutine interpolate_spectral_scalar(IPOPT,grid_in,grid_out, &
       MI,MO,KM,IBI,GI, &
       NO,RLAT,RLON,IBO,LO,GO,IRET)
```

What do these mean?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, I've set all those and merged to develop.
> 
> Moving on to spectral_interp_mod.F90:
> 
> ```
>   !> Interpolate spectral scalar.
>   !>
>   !> @param ipopt ???
>   !> @param grid_in ???
>   !> @param grid_out ???
>   !> @param MI ???
>   !> @param MO ???
>   !> @param KM ???
>   !> @param IBI ???
>   !> @param GI ???
>   !> @param NO ???
>   !> @param RLAT ???
>   !> @param RLON ???
>   !> @param IBO ???
>   !> @param LO ???
>   !> @param GO ???
>   !> @param IRET ???
>   !>
>   !! @author Mark Iredell @date 96-04-10
>   subroutine interpolate_spectral_scalar(IPOPT,grid_in,grid_out, &
>        MI,MO,KM,IBI,GI, &
>        NO,RLAT,RLON,IBO,LO,GO,IRET)
> ```
> 
> What do these mean?

ipopt - interpolation options; ipopt(1)=0 for triangular; ipopt(1)=1 for rhomboidal; ipopt(2) is truncation number (defaults to a sensible truncation if ipopt(2)=-1).
grid_in - input grid descriptor.
grid_out - output grid descriptor.
mi - skip number between input grid fields if km>1 or dimension of input grid fields if km=1.
mo - skip number between output grid fields if km>1 or dimension of output grid fields if km=1.
km - number of fields to interpolate.
ibi -input bitmap flags (Must be all 0. Routine does not do bitmapped interpolation.)
gi - input fields to interpolate.
no - number of output points.
rlat - output latitudes in degrees.
rlon - output longitudes in degrees.
ibo - output bitmap flags.
lo - output bitmaps.
go - output fields interpolated.
iret - return code. 0/non-0 - successful/not successful.

Most of these have been defined already farther down the routine.

**Comment by GeorgeGayno-NOAA** [comment]
ui - input u-component fields to interpolate
vi - input v-component fields to interpolate
uo - output u-component fields interpolated
vo - output v-component fields interpolated
crot - vector rotation cosines
srot - vector rotation sines.

**Comment by edwardhartnett** [comment]
OK, excellent. We are down to the very last file with ??? in it! ip_station_points_grid_mod.F90:

 ```
 !> Interpolate gridded data to a series of station points.
  !>
  !> @param[in] self The grid.
  !> @param[in] IOPT ???
  !> @param[in] NPTS ???
  !> @param[in] FILL ???
  !> @param[inout] XPTS ???
  !> @param[inout] YPTS ???
  !> @param[inout] RLON ???
  !> @param[inout] RLAT ???
  !> @param[out] NRET ???
  !> @param[out] CROT ???
  !> @param[out] SROT ???
  !> @param[out] XLON ???
  !> @param[out] XLAT ???
  !> @param[out] YLON ???
  !> @param[out] YLAT ???
  !> @param[out] AREA ???
  !>
  !> @author Kyle Gerheiser @date 7/21/21
  SUBROUTINE GDSWZD_station_points(self,IOPT,NPTS, &

```
Would these get the same descriptions as the same-named ones in other mod files?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, excellent. We are down to the very last file with ??? in it! ip_station_points_grid_mod.F90:
> 
> ```
> !> Interpolate gridded data to a series of station points.
>  !>
>  !> @param[in] self The grid.
>  !> @param[in] IOPT ???
>  !> @param[in] NPTS ???
>  !> @param[in] FILL ???
>  !> @param[inout] XPTS ???
>  !> @param[inout] YPTS ???
>  !> @param[inout] RLON ???
>  !> @param[inout] RLAT ???
>  !> @param[out] NRET ???
>  !> @param[out] CROT ???
>  !> @param[out] SROT ???
>  !> @param[out] XLON ???
>  !> @param[out] XLAT ???
>  !> @param[out] YLON ???
>  !> @param[out] YLAT ???
>  !> @param[out] AREA ???
>  !>
>  !> @author Kyle Gerheiser @date 7/21/21
>  SUBROUTINE GDSWZD_station_points(self,IOPT,NPTS, &
> ```
> 
> Would these get the same descriptions as the same-named ones in other mod files?

Yes, the descriptions are the same. However, this routine works for random points, not another grid. Therefore, IPOT must be minus 1 (return grid coordinates for selected earth coordinates). In other words, RLAT and RLON must always be input. And XPTS and YPTS are always output. The other fields - CROT, SROT, XLON, XLAT, YLON, YLAT and AREA can only be computed for a grid - not station points. So, those arguments should be removed at some point.
